version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"   # HTTP
      - "8443:443"  # HTTPS
    volumes:
      - ./html:/usr/share/nginx/html           # Mount static files
      - ./nginx.conf:/etc/nginx/nginx.conf     # Mount custom Nginx configuration
      # - ./certs:/etc/nginx/certs               # Mount SSL certificates (optional for reuse)